### ISSUE TITLE
Change screen-reader-text styles

### ISSUE THREAD

**Issue by GaryJones** [rianrietveld/leiden#1]
Bootstrap:

``` css
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  border: 0;
}
.sr-only-focusable:active,
.sr-only-focusable:focus {
  position: static;
  width: auto;
  height: auto;
  margin: 0;
  overflow: visible;
  clip: auto;
}
```

WordPress wp-admin (same base style, except for clip value format):

``` css
// Copied from wp-admin styles
.screen-reader-text,
.screen-reader-text span,
.ui-helper-hidden-accessible {
    position: absolute;
    margin: -1px;
    padding: 0;
    height: 1px;
    width: 1px;
    overflow: hidden;
    clip: rect(0 0 0 0);
    border: 0;
}

.screen-reader-text:focus {
    outline: 0;
}
```

HTML5 Boilerplate (different classes, different clip value format, different property order, but essentially the same):

``` css
.visuallyhidden {
    border: 0;
    clip: rect(0 0 0 0);
    height: 1px;
    margin: -1px;
    overflow: hidden;
    padding: 0;
    position: absolute;
    width: 1px;
}

.visuallyhidden.focusable:active,
.visuallyhidden.focusable:focus {
    clip: auto;
    height: auto;
    margin: 0;
    overflow: visible;
    position: static;
    width: auto;
}
```

Twenty Fourteen (simpler ruleset, but focus seems to be very specific to skiplink appearance):

``` css
.screen-reader-text {
    clip: rect(1px, 1px, 1px, 1px);
    position: absolute;
}

.screen-reader-text:focus {
    background-color: #f1f1f1;
    border-radius: 3px;
    box-shadow: 0 0 2px 2px rgba(0, 0, 0, 0.6);
    clip: auto;
    color: #21759b;
    display: block;
    font-size: 14px;
    font-weight: bold;
    height: auto;
    line-height: normal;
    padding: 15px 23px 14px;
    position: absolute;
    left: 5px;
    top: 5px;
    text-decoration: none;
    text-transform: none;
    width: auto;
    z-index: 100000; /* Above WP toolbar */
}
```

The point here is that all of them use the `clip` approach, rather than off-screen, which is what Leiden currently does. Moving an element to some distance off to the left can create memory issues on some devices due to the massive rendering box it has to handle. Using top means some browsers might scroll when the element gets focus, which might be confusing. 

Can Leiden switch to using a `clip` approach?
